namespace Offset{
enum Offsets {
 
//*NO NEED TO OPEN THAT BULLSHIT AGAIN AND AGAIN
getposition = 0x20A02D4, //CLASS TRANSFORM -> GET_POSITION_INJECTED
Camera = 0x20677B0, //CLASS CAMERA -> CAMERA GET_MAIN OR OTHER
gettransform = 0x209231C, //CLASS COMPONENT -> GET_TRANSFORM
WorldToScreenPoint = 0x2067458, //CLASS CAMERA -> WORLDTOSCREENPOINT_INJECTED


};
}

